### PR TITLE
bootstrap working and solved conflicts

### PR DESCRIPTION
**Pull request by mandeeps708**

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
why is their styling in html?

**Comment by mandeeps708** [comment]
Where?
Can you tell me the line number?

**Comment by amarjeetkapoor1** [comment]
line no 17,18 in index.html

**Comment by mandeeps708** [comment]
See here the changes made in this PR: https://github.com/amarjeetkapoor1/CivilOctave/pull/5/files
I am going to modify those in the next PR (may be today only) ;)

**Comment by amarjeetkapoor1** [comment]
I was not telling that you added them. I was asking why still their is styling in html code,  even after you have added css.

Also please put it on experimemtal to reveiw the changes by others

**Pull request merged**
